version: "3.8"
services:
  postgres:
    image: postgres:14.3-alpine
    # env_file:
    #   - .env
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      # - POSTGRES_USER=${DB_USER}
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
volumes:
  postgres:
